name: sklearn2codedev
dependencies:
    - python=3.6.2
    - nose
    - numpy=1.13.1
    - mako
    - sympy
    - scikit-learn
    - six
    - networkx
    - multipledispatch
    - pandas
    - pip:
        - toolz==0.8.2
        - sklearn-contrib-py-earth
        - frozendict
        - yapf
